name: Build 3DS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Upload 3DSX
        uses: actions/upload-artifact@v4
        with:
          name: 3oDoS-build
          path: |
            *.3dsx
            *.elf
